<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Close</name>
   <tag></tag>
   <elementGuidId>da43b9d9-e8ce-4aa6-91a8-6888ecfb409a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;ts-in-i-frame ltr&quot;]/div[@class=&quot;page-wrapper&quot;]/main[@class=&quot;content ng-scope&quot;]/div[@class=&quot;content-wrapper ng-scope&quot;]/section[@class=&quot;search&quot;]/section[1]/search-form[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;search-floating-input ng-scope ng-isolate-scope&quot;]/ts-search-depart-date[@class=&quot;floating-datepicker ng-scope ng-isolate-scope&quot;]/div[@class=&quot;popup&quot;]/footer[@class=&quot;popup-footer popup-footer--center&quot;]/ts-split-test[@class=&quot;ng-isolate-scope&quot;]/ng-transclude[@class=&quot;ng-scope&quot;]/footer[@class=&quot;popup-footer popup-footer--center ng-scope&quot;]/button[@class=&quot;popup-footer__back btn btn-link btn--small&quot;]/span[@class=&quot;ng-scope&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Flights (2)/iframe_travelstartIframe-dd7d2</value>
   </webElementProperties>
</WebElementEntity>
