<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_travelstartIframe-dd7d2</name>
   <tag></tag>
   <elementGuidId>a2043f71-f930-4881-8f3d-d3f5006084e1</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>travelstartIframe-dd7d2f33-38c3-4c69-baac-56d16157023b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.travelstart.ae/search-on-index?search=false&amp;show_banners=true&amp;log=false&amp;affCampaign=&amp;utm_source=affiliate&amp;utm_medium=189737&amp;isiframe=true&amp;landing_page=false&amp;iframeVersion=10&amp;host=https://www.phptravels.net/flightst</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;travelstartIframe-dd7d2f33-38c3-4c69-baac-56d16157023b&quot;)</value>
   </webElementProperties>
</WebElementEntity>
